# Generated by Django 4.2.16 on 2025-12-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyrecord',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_extra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='school.student'),
        ),
    ]
