# Generated by Django 4.2.16 on 2025-12-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_studentextra_profile_pic_and_more'),
    ]

    operations = [
    ]
