# Generated by Django 4.2.16 on 2025-12-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20251212_2311'),
    ]

    operations = [
    ]
